### ISSUE TITLE
"Done" but no output image

### ISSUE THREAD

**Issue by plutext** [Hyradus/ImageProcessingUtils#5]
I'm trying to convert a 1.6 GB jp2 to png (or jpeg)

When I "run all cells", it says:

Generating Images: 100%|██████| 1/1 [00:00<00:00, 5957.82File/s]

and I have a Processed.csv file containing:

Name,Status,Errors
myInput,Done,

but there is no output file.

I'm using the provided config, except IXT=jp2, OXT=png

I can see parallel_crops is supposed to be doing the work, but it returns immediately.

**Comment by Hyradus** [comment]
Hi, I should have fixed this, can you try again?
